---
title: "Note on variables applicable for classification"
date-modified: "2024-04-28"
---

Several variables [obtained during the acquisition
process](https://unstats.un.org/wiki/spaces/GWGSD/pages/101353236/ARCHIVE+Example+file+structures+for+web+scraped+and+scanner+data)
 are typically applicable for classification. An important consideration
is making sure that the appropriate variables are included when
acquisition is being discussed, as it may be challenging to expand the
set over time. The below table summarizes the variables commonly found
useful, although this table should not mean that all variables are used.
Studies should be done to make sure that only useful variables are used
in the classification process (for example some variables may not be of
much value to a classifier).

Table 1: Summary of typical variables in alternative data and their
application for classification

+:----------------:+:---------------:+:----------------------------------------------------------------:+:--------------:+
| **Value for      | **Variable**    | **Definition and note on its application for classification**    | **Note on data |
| classification** |                 |                                                                  | the variable   |
|                  |                 |                                                                  | is available   |
|                  |                 |                                                                  | in**           |
+------------------+-----------------+------------------------------------------------------------------+----------------+
| High             | Product name    | Actual product being sold. Useful for all but [Method            | This variable  |
|                  |                 | 1](method-1-attribute-based-classification-method.qmd).                                              | is usually     |
|                  |                 |                                                                  | available      |
|                  |                 |                                                                  | everywhere.    |
|                  |                 |                                                                  | Web scrape     |
|                  |                 |                                                                  | definitions of |
|                  |                 |                                                                  | product names  |
|                  |                 |                                                                  | may be         |
|                  |                 |                                                                  | unstable as a  |
|                  |                 |                                                                  | retailer may   |
|                  |                 |                                                                  | modify the     |
|                  |                 |                                                                  | name over time |
|                  |                 |                                                                  | (such as       |
|                  |                 |                                                                  | adding "SALE"  |
|                  |                 |                                                                  | at the end of  |
|                  |                 |                                                                  | the name).     |
+------------------+-----------------+------------------------------------------------------------------+----------------+
| High             | Retailer        | The retailer specific category or set of hierarchical            | Usually        |
|                  | category /      | categories. Most useful for rule-based approaches ([methods      | available as   |
|                  | categories      | 1](method-1-attribute-based-classification-method.qmd) and [2](method-2-pattern-matching-classification-method.qmd)).                     | retailer       |
|                  |                 |                                                                  | categories in  |
|                  |                 |                                                                  | scanner, or    |
|                  |                 |                                                                  | captured as a  |
|                  |                 |                                                                  | "breadcrumb"   |
|                  |                 |                                                                  | navigation     |
|                  |                 |                                                                  | variable on    |
|                  |                 |                                                                  | web scrape     |
|                  |                 |                                                                  | data.          |
+------------------+-----------------+------------------------------------------------------------------+----------------+
| High             | Product         | The unique identifier for the product, ideally the GTIN, the     | Usually        |
|                  | identifier      | first 2 codes of which are country, then 3-7 are                 | provided with  |
|                  | (ideally GTIN)  | manufacturer/producer specific. This variable is heavily used by | Scanner data,  |
|                  |                 | many NSOs. If GTIN is not available, other variables such as UPC | however not    |
|                  |                 | or SKU could be useful, but these provide less value for         | available in   |
|                  |                 | classification.                                                  | all countries. |
|                  |                 |                                                                  | Web scrape     |
|                  |                 |                                                                  | data usually   |
|                  |                 |                                                                  | does not       |
|                  |                 |                                                                  | contain GTINs  |
|                  |                 |                                                                  | but may have   |
|                  |                 |                                                                  | SKUs or other  |
|                  |                 |                                                                  | retailer       |
|                  |                 |                                                                  | specific       |
|                  |                 |                                                                  | product        |
|                  |                 |                                                                  | numbers.       |
+------------------+-----------------+------------------------------------------------------------------+----------------+
| Medium           | Description     | Text description of the product. Useful for all but [Method      | \              |
|                  |                 | 1](method-1-attribute-based-classification-method.qmd). For automated methods such as [methods       |                |
|                  |                 | 3](method-3-recommendation-machine-assisted-classification.qmd) and [4](method-4-machine-learning-classification-method.qmd), this is often the    |                |
|                  |                 | main variable that is used in the text processing pipeline to    |                |
|                  |                 | help predict the product class                                   |                |
+------------------+-----------------+------------------------------------------------------------------+----------------+
| Medium           | Brand           | Brand of the manufacturer. Usually used in concatenation, and    | \              |
|                  |                 | may be used by all but [method 1](method-1-attribute-based-classification-method.qmd). If GTIN is    |                |
|                  |                 | available, you can extract brand from there.                     |                |
+------------------+-----------------+------------------------------------------------------------------+----------------+
| Low (but high    | Product         | Materials or other attributes of the product. This may be useful | This variable  |
| for quality      | characteristics | if classification needs nuanced terms such as materials (e.g.    | is usually not |
| adjustment       | (sometimes      | clothing) and is usually only adopted when the process is highly | provided in    |
| methods)         | called          | automated (such as [Methods 3](method-3-recommendation-machine-assisted-classification.qmd) and               | scanner data,  |
|                  | features)       | [4](method-4-machine-learning-classification-method.qmd)). Methods that apply [quality adjustment     | but is         |
|                  |                 | (such as                                                         | available in   |
|                  |                 | hedonics)](quality-change-and-hedonic-estimation.qmd) | web scrape and |
|                  |                 | use this type of data heavily.                                   | administrative |
|                  |                 |                                                                  | data.          |
+------------------+-----------------+------------------------------------------------------------------+----------------+
