project:
  type: website

website:
  title: "Handbook on utilising new data sources in the production of consumer price statistics"
  site-url: https://un-task-team-for-scanner-data.github.io/cpi-new-data-sources-handbook/
  repo-url: https://github.com/UN-Task-Team-for-Scanner-Data/cpi-new-data-sources-handbook
  favicon: handbook\images\logo.png
  repo-branch: main
  repo-actions: [source, issue]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  navbar:
    background: primary
    logo: handbook/images/logo.png
    search: true
    title: "New data sources in consumer price statistics"
    right:
      - text: "About us"
        icon: person-raised-hand
        menu:
          - text: "About"
            href: about/index.qmd
            icon: people-fill
          - text: "How to contribute"
            href: about/contributing.qmd
            icon: pencil-square
          - text: "Style Guide"
            href: about/style-guide.qmd
            icon: text-left
      - text: "Related materials"
        icon: lightbulb
        menu:
          - text: "Prices Reproducibility Guidance"
            href: https://un-task-team-for-scanner-data.github.io/reproducibility-project/docs/
            icon: flask
          - text: "Open price statistics datasets"
            href: https://un-task-team-for-scanner-data.github.io/price-stats-data-catalogue/
            icon: database-check
          - text: "CPI Manual"
            href: https://www.imf.org/en/data/statistics/cpi-manual
            icon: journal-check
          - text: "Ottawa Group website"
            href: https://stats.unece.org/ottawagroup/
            icon: people
          - text: "CPI Expert Group website"
            href: https://unece.org/expert-group-consumer-price-indices
            icon: people

    left:
      - href: handbook/index.qmd
        icon: journal-bookmark
        text: Handbook
      - href: training/index.qmd
        text: Training Materials
        icon: play-btn-fill


  sidebar:
    - id: handbook
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - handbook/index.qmd
        - "---"
        - section: "Initial considerations"
          href: handbook/initial-considerations/index.qmd
          contents:
          - handbook/initial-considerations/overview-of-alternative-data-sources.qmd
          - handbook/initial-considerations/why-use-alternative-data-sources-strategic-motivations.qmd
          - handbook/initial-considerations/key-challenges-and-trade-offs.qmd
          - handbook/initial-considerations/key-decision-points.qmd
          - handbook/initial-considerations/resource-implications-and-organisational-readiness.qmd
        - handbook/cpi-production-system-requirements.qmd
        - handbook/quality-assurance.qmd
        - section: "Data selection and acquisition"
          href: handbook/selection-and-acquisition/index.qmd
          contents:
            - handbook/selection-and-acquisition/selection-of-categories.qmd
            - handbook/selection-and-acquisition/selection-of-retailers-for-alternative-data-sources.qmd
            - section: "Scanner data"
              href: handbook/selection-and-acquisition/scanner/index.qmd
              contents:
                - handbook/selection-and-acquisition/scanner/initial-steps-in-the-acquisition-of-scanner-data.qmd
                - handbook/selection-and-acquisition/scanner/data-requirements-specification-for-scanner-data.qmd
                - handbook/selection-and-acquisition/scanner/data-sharing-agreements.qmd
                - handbook/selection-and-acquisition/scanner/alternative-approaches-to-acquiring-scanner-data.qmd
                - handbook/selection-and-acquisition/scanner/monitoring-validation-and-plausibility-checks-for-scanner-data.qmd
            - section: "Web scraping"
              href: handbook/selection-and-acquisition/web-scraped/index.qmd
              contents:
                - handbook/selection-and-acquisition/web-scraped/different-approaches-to-accessing-web-scraped-data.qmd
                - handbook/selection-and-acquisition/web-scraped/strategies-available-for-in-house-web-scraping.qmd
                - handbook/selection-and-acquisition/web-scraped/data-requirements-specification-for-web-scraped-data.qmd
                - handbook/selection-and-acquisition/web-scraped/monitoring-validation-and-plausibility-checks-for-web-scraped-data.qmd
                - handbook/selection-and-acquisition/web-scraped/common-technical-problems-for-in-house-web-scraping.qmd
            - handbook/selection-and-acquisition/example-file-structures-for-web-scraped-and-scanner-data.qmd
            - handbook/selection-and-acquisition/collection-of-data-via-apis.qmd
            - handbook/selection-and-acquisition/dealing-with-unexpected-data-gaps.qmd
        - section: "Preparation of data"
          href: handbook/preparation/index.qmd
          contents:
            - handbook/preparation/product-sampling-for-price-index-calculation.qmd
            - handbook/preparation/standardising-the-data.qmd
            - handbook/preparation/aggregation-across-time-and-outlets.qmd
            - handbook/preparation/identifying-unique-products.qmd
            - handbook/preparation/treatment-of-discounts-and-refunds.qmd
        - section: "Classification"
          href: handbook/classification/index.qmd
          contents:
            - section: "Pre-conditions and deciding on appropriate classification methods"
              href: handbook/classification/pre-conditions-and-deciding-on-appropriate-classification-methods.qmd
              contents:
                - handbook/classification/note-on-variables-applicable-for-classification.qmd
            - handbook/classification/method-0-manual-labelling-or-validation-of-predicted-labels.qmd
            - handbook/classification/method-1-attribute-based-classification-method.qmd
            - handbook/classification/method-2-pattern-matching-classification-method.qmd
            - handbook/classification/method-3-recommendation-machine-assisted-classification.qmd
            - section: "Method 4: Machine Learning classification method"
              href: handbook/classification/method-4-machine-learning-classification-method.qmd
              contents:
                - handbook/classification/how-to-evaluate-classification-methods.qmd
                - handbook/classification/working-with-class-imbalance.qmd
            - section: "Operational best practices"
              href: handbook/classification/operational-best-practices.qmd
              contents:
                - handbook/classification/designing-the-classification-step-operational-considerations.qmd
        - section: "Data filtering and missing prices"
          href: handbook/filtering/index.qmd
          contents:
            - handbook/filtering/outlier-filter.qmd
            - handbook/filtering/dumping-filter.qmd
            - handbook/filtering/low-sales-filter.qmd
            - handbook/filtering/current-practice-of-data-filtering.qmd
            - handbook/filtering/treatment-of-missing-prices.qmd
        - section: "Price index methods"
          href: handbook/index-methods/index.qmd
          contents:
            - section: "Bilateral price index methods"
              href: handbook/index-methods/bilateral-price-index-methods.qmd
              contents:
                - handbook/index-methods/example-of-chain-drift.qmd
            - handbook/index-methods/multilateral-price-index-methods.qmd
            - handbook/index-methods/extension-methods.qmd
            - handbook/index-methods/decomposition.qmd
            - section: "Choosing an index method"
              href: handbook/index-methods/choosing-an-index-method.qmd
              contents:
                - handbook/index-methods/methods-for-when-expenditure-data-are-available.qmd
                - handbook/index-methods/methods-for-when-expenditure-data-are-not-available.qmd
            - handbook/index-methods/deriving-proxy-weights-for-web-scraped-data.qmd
        - handbook/aggregation.qmd
        - section: "Other uses of alternative data"
          href: handbook/other-uses/index.qmd
          contents:
            - handbook/other-uses/other-uses-of-alternative-data-beyond-cpi.qmd
            - handbook/other-uses/other-uses-of-alternative-data-within-cpi.qmd
        - section: "Other considerations"
          href: handbook/other-considerations/index.qmd
          contents:
            - handbook/other-considerations/seasonal-products.qmd
            - handbook/other-considerations/quality-change-and-hedonic-estimation.qmd
        - handbook/implementation.qmd
        - "---"
        - handbook/glossary.qmd
        - handbook/acknowledgements.qmd


language:
  title-block-modified: "Last updated"

format:
  html:
    date-format: "D MMMM YYYY"
    toc: true
    toc-expand: 2
    theme:
      light: flatly
      dark: cyborg
    css: styles.css