---
title: "Bilateral price index methods"
---

This section presents the basic, commonly known formulas of bilateral price indices. Like the [Multilateral price index methods](multilateral-price-index-methods.qmd) section, it does not include a broader discussion of the legitimacy of using individual indices. For an overview of approaches to select an index method, see the [Choosing an index method](choosing-an-index-method.qmd) section.

There are many methods available to calculate a price index. Bilateral price indices use observations from two periods, for instance, they compare the current period with the base one. Unweighted indices use only prices available in the base period and the current period, while weighted indices also use expenditure information for these two periods if available.

\

**Page information**

+---------------------+--------------------------------------------------------------------------------------------+
| Version             | v8                                                                                         |
+---------------------+--------------------------------------------------------------------------------------------+
| Last updated on     | 2021-09-30                                                                                 |
+---------------------+--------------------------------------------------------------------------------------------+
| Summary of changes  | Initial publication                                                                        |
+---------------------+--------------------------------------------------------------------------------------------+
| Page History        | [See here](https://unstats.un.org/wiki/pages/viewpreviousversions.action?pageId=240910487) |
+---------------------+--------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

# Unweighted indices {#Bilateralpriceindexmethods-Unweightedindices}

Three indices are commonly described -- the Jevons, Dudot, and Carli. The Jevons can be written as follows:

$P_{J}^{0, t}=\prod_{i \in G_{0, t}} \left(\frac{p_{i}^{t}}{p_{i}^{0}}\right)^{\frac{1}{N_{0, t}}}$

where $G_{0,t}$ is a set of matched products in both months 0 and t, $p_i^{\tau}$ denotes the price of the i-th product at time $\tau \in \{0,t\}$ and $N_{0,t}= \operatorname{card} G_{0,t}$.

The Dutot price index can be written as:

$P_{D}^{0, t}=\frac{\sum\limits_{i \in G_{0, t}} p_{i}^{t}}{\sum\limits_{i \in G_{0, t}} p_{i}^{0}}$

And the Carli price index is an arithmetic mean of price relatives, i.e.

$P_{C}^{0, t}=\frac{1}{N_{0, t}} \sum\limits_{i \in G_{0, t}} \frac{p_{i}^{t}}{p_{i}^{0}}$

For a homogeneous group of products, a Dutot or a Carruthers-Sellwood-Ward-Dalen (a geometric mean of the Carli and the harmonic mean of price relatives (Lippe, 2007)) can be used. At the same time, the Carli formula overestimates real price change (CPI Manual, 2020), thus the Jevons is recommended by the European Commission when expenditure information is not available in a data set (Eurostat, 2018) and by the 1996 Boskin Commission in the USA, which recommended a shift rom a Carli-like index (Levell, 2015). Eurostat regulations do not allow the use of the Carli index in the construction of the members' Harmonized Index of Consumer Prices (HICP). Furthermore, there has been a general trend of replacing the Carli index with the Jevons or Dudot formulas (Evans, 2012).

A less common but worth noting unweighted price index formula is the Balk-Mehrhoff-Walsh (BMW) index (Eurostat, 2018), which can be expressed as follows:

$P_{BMW}^{0, t}=\sum\limits_{i \in G_{0, t}} \frac{p_{i}^{t}}{p_{i}^{0}} \frac{\sqrt{\frac{p_{i}^{0}}{p_{i}^{t}}}}{\sum\limits_{k \in G_{0, t}} \sqrt{\frac{p_{k}^{0}}{p_{k}^{t}}}}$

# Weighted indices {#Bilateralpriceindexmethods-Weightedindices}

Since scanner data contain information about expenditures, which can have a big impact on a price index, quantities $q_i^t$ of sold products can be used to calculate weighted bilateral indices. Two weighted indices which figure prominently in the literature, are the Laspeyres (1871) and Paasche (1874), given respectively by

$P_{La}^{0, t}=\frac{\sum\limits_{i \in G_{0, t}} q_{i}^{0} p_{i}^{t}}{\sum\limits_{i \in G_{0, t}} q_{i}^{0} p_{i}^{0}}$

and 

$P_{Pa}^{0, t}=\frac{\sum\limits_{i \in G_{0, t}} q_{i}^{t} p_{i}^{t}}{\sum\limits_{i \in G_{0, t}} q_{i}^{t} p_{i}^{0}}$

Superlative price indices are also very prominent. Superlative indices can be expected to approximate the Cost of Living Index (COLI), and are 'exact' for a flexible aggregator, which is a second-order approximation to an arbitrary production, cost, utility or distance function and they treat prices and quantities equally across periods. The Fisher, Törnqvist, and Walsh price indices are examples of of superlative indices. Superlatives are also commonly accepted as base formulas in the [multilateral](multilateral-price-index-methods.qmd) GEKS method (Diewert and Fox, 2017). 

The Fisher (1922) formula, which can be written as:

$P_{F}^{0, t}=\sqrt{P_{La}^{0, t} \cdot P_{Pa}^{0, t}}$

where $P_{La}^{0, t}$ and $P_{Pa}^{0, t}$ denote the Laspeyres and Paasche price index respectively. The Törnqvist can be written as

$P_{T}^{0, t}=\prod\limits_{i \in G_{0, t}} \left(\frac{p_{i}^{t}}{p_{i}^{0}}\right)^{\frac{s_{i}^{0}+s_{i}^{t}}{2}}$

where $s_i^0$ and $s_i^t$ denote the expenditure shares of matched products in months 0 and t. Walsh can be written as

$P_{W}^{0, t}=\frac{\sum\limits_{i \in G_{0, t}} \sqrt{q_{i}^{0} q_{i}^{t}} \cdot p_{i}^{t}}{\sum\limits_{i \in G_{0, t}} \sqrt{q_{i}^{0} q_{i}^{t}} \cdot p_{i}^{0}}$

Some statisticians use the Sato-Vartia index (Sato 1976; Vartia 1976) for scanner data case due to its good axiomatic properties (Lippe 2007; Abe & Prasada Rao 2019). Following Sato (1976), the log-change price index has the following generic form:

$\ln P_{S V}^{0, t}=\sum_{i=1}^{N} \phi_{i}^{0, t} \ln \left(\frac{p_{i}^{t}}{p_{i}^{0}}\right)$

where 

$\phi_{i}^{0, t}=\frac{ \frac{s_{i}^{t}-s_{i}^{0}}{\ln \left(s_{i}^{t}\right)-\ln \left(s_{i}^{0}\right)}}{ \sum\limits_{k \in G_{0, t}} \frac{s_{k}^{t}-s_{k}^{0}}{\ln \left(s_{k}^{t}\right)-\ln \left(s_{k}^{0}\right)}}$

A wide range of price indices, including an overview of their properties and relationships between them, can be found in the CPI Manual (2020), [Consumer Price Index Theory](https://www.imf.org/en/Data/Statistics/cpi-manual), von der Lippe, P. (2007), and [Eurostat (2018)](https://ec.europa.eu/eurostat/documents/3859598/9479325/KS-GQ-17-015-EN-N.pdf/d5e63427-c588-479f-9b19-f4b4d698f2a2). Some less familiar and non-classical formulas of weighted price indices can be found, for example, in the works of Białek (2014) or Białek (2020).

# Chaining indices {#Bilateralpriceindexmethods-Chainingindices}

In the \"direct\" approach, the resulting price index $P^{0,t}$ is not influenced by what happens to prices and quantities in the intermediate points in time: 1, 2, \... , t-1.  The idea of chain indices is that a longer interval is partitioned into a subset of smaller intervals on which bilateral indices are calculated and subsequently combined (chained). In other words, a chain index provides a measure of the cumulative effect of successive steps from 0 to 1, 1 to 2, \..., t-1 to t (Lippe, 2007). In general, the chain index takes the following form:

$P_{ch}^{0, t}=\prod_{s=1}^{t} P^{s-1, s}$

where the linking formula $P^{s-1, s}$ is any bilateral price index. For instance, one can consider the chain Fisher price index defined as follows

$P_{ch-F}^{0, t}=\prod_{s=1}^{t} P_{F}^{s-1, s}$

------------------------------------------------------------------------

# References {#Bilateralpriceindexmethods-References}

\(1\) Abe, N., Prasada Rao, D. (2019). Multilateral Sato--Vartia index for international comparisons of prices and real expenditures. *RCESR Discussion Paper Series*. <https://risk.ier.hit-u.ac.jp/English/pdf/dp19-1_rcesr.pdf> 

\(2\) Białek J. (2014), Simulation Study of an Original Price Index Formula, Communications in Statistics - Simulation and Computation, 43(2), 285-297. <https://ideas.repec.org/a/csb/stintr/v15y2014i1p83-96.html> 

\(3\) Białek, J. (2020), Proposition of a hybrid price index formula for the Consumer Price Index measurement*,* Equilibrium. *Quarterly Journal of Economics and Economic Policy*, 15(4), 697-716. <https://ideas.repec.org/a/pes/ierequ/v15y2020i4p697-716.html>

\(4\) Carli, G. (1804). Del valore e della proporzione de'metalli monetati. *Scrittori Classici Italiani di Economia Politica*, 13, 297-336.

\(5\) Carruthers, A., Sellwood, D., Ward, P. (1980). Recent developments in the retail prices index. *Journal of the Royal Statistical Society*. Series D (The Statistician), 29(1), 1--32. <https://www.jstor.org/stable/pdf/2987492.pdf> 

\(6\) Chessa, A.G., Verburg, J., and Willenborg, L. (2017). A comparison of price index methods for scanner data. *Paper presented at the 15^th^ Meeting of the Ottawa Group*. <https://stats.unece.org/ottawagroup/download/f460.pdf>

\(7\) Consumer Price Index Manual. Concepts and Methods. (2020). IMF/ILO/Eurostat/UNECE/OECD/The World Bank. <https://www.imf.org/en/Data/Statistics/cpi-manual>

\(8\) Consumer Price Index Theory (draft, online). <https://www.imf.org/en/Data/Statistics/cpi-manual>

\(9\) Diewert, W. E. (1976). Exact and superlative index numbers. *Journal of Econometrics,* 4, 114-145.

\(10\) Diewert, W. E., Fox, K. J. (2017). Substitution Bias in Multilateral Methods for CPI Construction using Scanner Data. *Discussion paper 17-02*, Vancouver School of Economics, The University of British Columbia, Vancouver, Canada.

\(11\) Dutot, F. (1738). Reflexions Politiques sur les Finances et le Commerce. The Hague: LesFreres.

\(12\) Evans, B. (2012). International comparison of the formula effect between the CPI and RPI. Office for National Statistics. Newport. <https://www.semanticscholar.org/paper/International-Comparison-of-the-Formula-Effect-the-Evans/66673228f9665c9cd31011da1ef932eee394afa9>

\(13\) Eurostat 2017. *Practical guide for processing supermarket scanner data.* Eurostat. <https://circabc.europa.eu/sd/a/8e1333df-ca16-40fc-bc6a-1ce1be37247c/Practical-Guide-Supermarket-Scanner-Data-September-2017.pdf>

\(14\) Eurostat (2018) Harmonized Index of Consumer Prices (HICP): Methodological Manual. November 2018. <https://ec.europa.eu/eurostat/documents/3859598/9479325/KS-GQ-17-015-EN-N.pdf/d5e63427-c588-479f-9b19-f4b4d698f2a2>

\(15\) Fisher, I. (1922). The making of index numbers: a study of their varieties, tests, and reliability*.* Houghton Mifflin.

\(16\) Jevons, W. S. (1865). The variation of prices and the value of the currency since 1782. J. Statist. Soc. Lond., 28, 294-320.

\(17\) Laspeyres, K. (1871). IX. Die Berechnung einer mittleren Waarenpreissteigerung. *Jahrbücher für Nationalökonomie und Statistik*,16 (1), 296--318.

\(18\) Levell, P. (2015).  Is the Carli index flawed?: assessing the case for the new retail price index RPIJ. *Journal of the Royal Statistical Society*: Series A (Statistics in Society)*,* 178 (2), 303--336.

\(19\) Paasche, H. (1874). Über die Preisentwicklung der letzten Jahre nach den Hamburger Börsen-notirungen. Jahrbücher für Nationalökonomie und Statistik, 168--178.

\(19\) Sato, K. (1976). The ideal log-change index number. *The Review of Economics and Statistics, *223--228.

\(20\) Törnqvist, L. (1936). The Bank of Finland\'s Consumption Price Index, Bank of Finland Monthly Bulletin 10, 1-8.

\(21\) Walsh, C. M. (1901). The Measurement of General Exchange Value. Macmillan and Co.

\(22\) Vartia, Y. 0. (1976). Ideal Log-Change Index Numbers. *Scandinavian Journal of Statistics, *3(3), 121--126. <https://www.jstor.org/stable/4615624> 

\(23\) von der Lippe, P. (2007). Index Theory and Price Statistics*.* Peter Lang.
