---
title: "Classification"
---

The goal of this section is to provide guidance on the critical step of classifying new data sources and make them ready for price index compilation. Similar to other applications within official statistics (section 5.2. and 5.3 of [the GSBPM](https://unece.org/sites/default/files/2023-11/GSBPM%20v5_1.pdf) define this task), classification must be done to calculate low level aggregates by strata. Specifically, once [data preparation steps](https://unstats.un.org/wiki/display/GWGSD/Preparation+of+data) are complete, all prices in each retailer dataset need to be categorised to a classification system (or taxonomy) utilised by the NSO as part of index stratification. In other words, the output of the classification step is to assign all prices in the dataset to a category that will support the stratification process [in the aggregation step](https://unstats.un.org/wiki/display/GWGSD/Aggregation) (1, 2, 3). Categorising prices to each geographic strata also used for aggregation, and the assigning of data to structured variables used for [quality adjustment methods](quality-change-and-hedonic-estimation.qmd), can both also be considered classification. Furthermore, the activity of classification is done both initially when preparing to integrate a new data source into the CPI or to support the research process, and on a recurrent basis once the dataset is in production.

While classification activities can be outsourced (or already classified data could be [acquired](https://unstats.un.org/wiki/display/GWGSD/Data+acquisition)), typically NSOs have chosen to do classification in-house. The below guidance provides an overview of the common classification methods and demonstrates notable aspects using code notebooks and public data. Each method is outlined

1.  with the initial process to classify data to initially integrate a dataset into production,
2.  the regular process of classifying data once in production, and
3.  quality and process considerations to maintain the classification method.

The below guidance also provides key considerations necessary to consider before beginning classification and how to choose an appropriate classification method, as well as best practices of combining classification methods to achieve better performance.

**Page information**

+---------------------+--------------------------------------------------------------------------------------------+
| Version             | v7                                                                                         |
+---------------------+--------------------------------------------------------------------------------------------+
| Last updated on     | 2025-04-28                                                                                 |
+---------------------+--------------------------------------------------------------------------------------------+
| Summary of changes  | Publish new set of pages as part of 2025 CPI EG                                            |
+---------------------+--------------------------------------------------------------------------------------------+
| Page history        | [See here](https://unstats.un.org/wiki/pages/viewpreviousversions.action?pageId=240910479) |
+---------------------+--------------------------------------------------------------------------------------------+

Section contents:

- [Pre-conditions and deciding on appropriate classification methods](pre-conditions-and-deciding-on-appropriate-classification-methods.qmd) --- There are several factors that NSO typically consider when approaching or implementing classification, such as the scale and complexity of the task, whether this is just the initial phase of classification or recurrent classification in production, or the structure and quality of the data. Evaluating these factors is useful to select the method(s) most appropriate for each use case.
  - [Note on variables applicable for classification](note-on-variables-applicable-for-classification.qmd) --- Several variables obtained during the acquisition process  are typically applicable for classification. 
- [Method 0: Manual labelling or validation of predicted labels](method-0-manual-labelling-or-validation-of-predicted-labels.qmd) --- Manual classification involves each unique product being manually assigned a classification class. This is often described as labelling, and those who specialize in the task, labellers This method can also be used to validate classification done automatically by other methods. 
- [Method 1: Attribute-based classification method](method-1-attribute-based-classification-method.qmd) --- Attribute-based classification involves classifying observations in the data by mapping structured variables or attributes available in the alternative data file to the necessary taxonomy classes. 
- [Method 2: Pattern matching classification method](method-2-pattern-matching-classification-method.qmd) --- Pattern based classification involves mapping individual records to the taxonomy classes of interest according to patterns present in their descriptive attributes. For instance, patterns in the categories of the alternative data, patterns in the product name, or specific keywords in the product description - could all be used to classify a set of individual records. 
- [Method 3: Recommendation / Machine-assisted classification](method-3-recommendation-machine-assisted-classification.qmd) --- Machine-assisted classification is still a manual classification technique and therefore the ideas in the manual classification chapter are still valid. The key difference is the addition of a recommendation system that supports labellers in identifying the most appropriate class. Every product is still manually scrutinised, but machine-assistance may improve efficiency and potentially quality by offering recommendations. 
- [Method 4: Machine Learning classification method](method-4-machine-learning-classification-method.qmd) --- Machine Learning (ML) can be a stable solution for classifying unique products when an NSO starts to use new data sources at scale. NSOs typically use supervised ML methods whereby a manually annotated dataset is used to train a classifier to predict all new unique products as part of recurrent classification. 
  - [How to evaluate classification methods](how-to-evaluate-classification-methods.qmd) --- There are numerous metrics that can be tracked and applied when evaluating how well a classifier performs. 
  - [Working with class imbalance](working-with-class-imbalance.qmd) --- Datasets NSOs need to classify are typically not equally distributed, as some classes have many records (i.e. unique products) while others have only a few. This requires additional steps to be taken when designing and testing classifiers. 
- [Operational best practices](operational-best-practices.qmd) --- Once NSOs select and develop an appropriate classification method, they have to implement it. This section includes articles on appropriate ways to operationalize classification. 
  - [Designing the classification step: operational considerations](designing-the-classification-step-operational-considerations.qmd) --- This section provides context about where and how the classification step fits into the rest of the pipeline processing alternative data to create elementary price indices, as well as some important considerations and options when setting up the classification process. This article can also be seen as a companion to the pre-conditions to classification section, helping the NSO design the operational process for the individual or blended method that will be chosen.

**Note**: All code notebooks demonstrating these methods, as well as diagrams will be saved in a public way for all to see, such as on our [classification_methods GitHub repository](https://github.com/UN-Task-Team-for-Scanner-Data/classification_methods).

Additional guidance is still being developed

Workstream 2 is still finalizing a few additional topics of guidance. See [slide 6 of the 2025 CPI Expert Group presentation](https://unece.org/sites/default/files/2025-04/1.3_UN%20Task%20Team.pdf) for more on what is being developed.

\

## References  {#Classification-References}

\(1\) Practical guidelines on web scraping for the HICP (2020) <https://ec.europa.eu/eurostat/documents/272892/12032198/Guidelines-web-scraping-HICP-11-2020.pdf/>

\(2\) See chapters 5, 8, and 10 for more information in Consumer Prices Index Manual (2020). <https://www.imf.org/-/media/Files/Data/CPI/cpi-manual-concepts-and-methods.ashx>

\(3\) Practical Guide for Processing Supermarket Scanner Data, Eurostat (2017) <https://circabc.europa.eu/sd/a/8e1333df-ca16-40fc-bc6a-1ce1be37247c/Practical-Guide-Supermarket-Scanner-Data-September-2017.pdf>
