---
title: "Example file structures for web scraped and scanner data"
---

This page contains example variables and data types for new data sources\

**Page information**

+----------------------+--------------------------------------------------------------------------------------------+
| Version              | v2                                                                                         |
+----------------------+--------------------------------------------------------------------------------------------+
| Last updated on      | 2021-08-02                                                                                 |
+----------------------+--------------------------------------------------------------------------------------------+
| Summary of changes   | Initial publication version                                                                |
+----------------------+--------------------------------------------------------------------------------------------+
| Page History         | [See here](https://unstats.un.org/wiki/pages/viewpreviousversions.action?pageId=240910470) |
+----------------------+--------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

# Typical file structures {#Examplefilestructuresforwebscrapedandscannerdata-Typicalfilestructures}

Table 1 provides some example file structures for web scraped and scanner data for comparison purposes using groceries as a case study.

Table 1: typical file structures

+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| **Scanner data**                                                                                          | **Web scraped data**                                                                                                       |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| **Variable**                   | **Format**          | **Example**                                        | **Variable**                             | **Format**          | **Example**                                               |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| *Date*                         | Numeric or date     | 20180104,                                          | *Date*                                   | Numeric or date     | 20180104,                                                 |
|                                |                     |                                                    |                                          |                     |                                                           |
|                                |                     | 01/04/2018                                         |                                          |                     | 01/04/2018                                                |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| *Store ID*                     | Text or numeric     | Store_0001                                         | \                                        | \                   | \                                                         |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| *Region*                       | Text or numeric     | Sydney                                             | \                                        | \                   | \                                                         |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| *Product identifier*           | Numeric or text     | ABC_0001                                           | *Product identifier*                     | Numeric or text     | ABC_0001                                                  |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| *Retailer classifications*     | Text or numeric     | Grocery -- Dairy -- Cheese -- Entertainment Cheese | *Retailer classifications*               | Text or numeric     | Grocery -- Dairy Products -- Cheese -- Block Dairy Cheese |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| *Description*                  | Text                | 'Tasty' Brand Brie Cheese 200g                     | *Description*                            | Text                | 'Tasty' Brand Brie Cheese 200g                            |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| *Quantity (scanner data only)* | Numeric             | 61 units                                           | \                                        | \                   | \                                                         |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| *Turnover*                     | Numeric or currency | \$501                                              | \                                        | \                   | \                                                         |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
| \                              | \                   | \                                                  | *Observed price (web scraped data only)* | Numeric or currency | \$8.213                                                   |
+--------------------------------+---------------------+----------------------------------------------------+------------------------------------------+---------------------+-----------------------------------------------------------+
