---
title: "Glossary"
---

This page contains the handbook glossary.\

**Page information**

+---------------------+--------------------------------------------------------------------------------------------+
| Version             | v2                                                                                         |
+---------------------+--------------------------------------------------------------------------------------------+
| Last updated on     | 2024-03-27                                                                                 |
+---------------------+--------------------------------------------------------------------------------------------+
| Summary of changes  | Initial publication version                                                                |
+---------------------+--------------------------------------------------------------------------------------------+
| Page History        | [See here](https://unstats.un.org/wiki/pages/viewpreviousversions.action?pageId=240910449) |
+---------------------+--------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

# Introduction {#Glossary-Introduction}

The first challenge for any international guidance manual is to harmonise the terminology used. This is particular true in the world of consumer price statistics, where different countries and users use different terms to discuss the same concepts. In this glossary, we have not only included words/phrases that require defining, we also have tried to note where different terminology is sometimes used. We start this page by looking at some of the key areas that require definition, before moving onto the glossary in its more conventional sense. 

# Definition of a product {#Glossary-Definitionofaproduct}

One of the areas with the biggest difference in terminology is how different countries describe the individual products whose prices (and expenditure, if available) are used to compile consumer price statistics. For this wiki, we have used the following terminology.

Table 1: summary of terminology used to describe products

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+------------------------------------------------------------------------------------------------------+----------------------------+----------------------------------------------------------------------------------------------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lowest level (observation)                                                                                                                                      | *Aggregation over time* | Average price for a specific time period (e.g. a month), a specific outlet and specific article code | *Aggregation over outlets* | Average price for a specific time period and specific article code, but over several outlets | *Aggregation over* *article* *codes* | Average price for a specific time period but over several outlets and article codes = **Homogeneous product**                                                  |
|                                                                                                                                                                 |                         |                                                                                                      |                            |                                                                                              |                                      |                                                                                                                                                                |
|                                                                                                                                                                 | **→ **                  |                                                                                                      | ***→ ***                   |                                                                                              | ***→ ***                             |                                                                                                                                                                |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+------------------------------------------------------------------------------------------------------+----------------------------+----------------------------------------------------------------------------------------------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Observation**: at a specific time, from a specific outlet, for a specific **article code**, under specific terms of supply, and for which a price is observed | \                       | \                                                                                                    | (if available)             | \                                                                                            | \                                    | **Homogeneous** **product**: set of individual products among which there are no significant quality differences and for which an average price is calculated; |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+------------------------------------------------------------------------------------------------------+----------------------------+----------------------------------------------------------------------------------------------+--------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Individual product**: depending on context, this can refer to anything between an observation and a homogeneous product                                                                                                                                                                                                                                                                                                                                           | \                                                                                                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+

Other words/phrases often used here include Global Trade Item Number (GTIN), item code and item. The glossary in the [Consumer Price Index (CPI) Manual](https://www.ons.gov.uk/economy/inflationandpriceindices/methodologies/consumerpricesindicestechnicalmanual2019) uses the term **variety** to mean \"the individual product for which prices are collected during the collection period. It includes the detailed specification of the product or item observed\". However, for this wiki, we have chosen to use the terminology **article code **for this purpose. We use the term variety to mean the different varieties of products you can get that have the same article code, for example different sizes or colours.

# Glossary of terms {#Glossary-Glossaryofterms}

Table 2: glossary of terms

+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Term                  | Definition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Alternative Data      | Data that differ from the traditional form of data typically used by National Statistical Offices (NSOs) by collection method (web scraped or bulk data delivery) or by type (Transaction records). This category can encompass transaction data, administrative data, or data collected through web scraping outside an NSO's typical survey and collection framework. Some NSOs may have long histories of using data sources (especially administrative date) that may be considered novel and alternative by others. |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| \                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Article Drift         | Chain drift can be formalized in terms of the violation of the multi period identity test. According to this test one can expect, that when all prices and quantities in a current period revert back to their values from the base period, then the index should indicate no price change and it equals 1. For a worked example of chain drift please see Section [Example of chain drift](https://unstats.un.org/wiki/display/GWGSD/Example+of+chain+drift).                                                           |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Article Code          | The individual product for which prices are collected.                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Chain Drift           | Chain drift can be formalised in terms of the violation of the multi period identity test. According to this test one can expect, that when all prices and quantities in a current period revert back to their values from the base period, then the index should indicate no price change and it equals 1. For a worked example of chain drift please see Section [Example of chain drift](https://unstats.un.org/wiki/display/GWGSD/Example+of+chain+drift).                                                           |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Consumption Patterns  | A household\'s allocation of expenditures across different consumption categories, such as food, housing, clothing, and transportation, how consumers act, how loyal they are to brands and how they react to new products and services.                                                                                                                                                                                                                                                                                 |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CPI                   | Consumer Price Index is a measure of the average prices of goods sold to consumers.                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Elementary Aggregates | Elementary aggregates (EAs) represent the lowest level -- both in the product and the geography dimensions -- where price indices are first calculated using prices for individual products.                                                                                                                                                                                                                                                                                                                             |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Homogeneous Product   | See above. set of individual products among which there are no significant quality differences and for which an average price is calculated;                                                                                                                                                                                                                                                                                                                                                                             |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Individual Product    | See above. depending on context, this can refer to anything between an observation and a homogeneous product                                                                                                                                                                                                                                                                                                                                                                                                             |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Non-Survey Data       | Data obtained without the sampling methods typically used for traditional data used by NSOs.                                                                                                                                                                                                                                                                                                                                                                                                                             |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| NSO/NSI               | National Statistical Office/ National Statistical Institute. In this wiki, we use National Statistical Office (NSOs) but both are valid.                                                                                                                                                                                                                                                                                                                                                                                 |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Observation           | See above. At a specific time, from a specific outlet, for a specific **article code**, under specific terms of supply, and for which a price is observed.                                                                                                                                                                                                                                                                                                                                                               |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Periodic Resampling   | Sources of time series data which are periodic measurements or observations.                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Probability Sampling  | The selection of a sample from a population that is random or by change.                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sampling Error        | A statistical error occurs when a sample is selected that is not representative of the sample being studied and is known as a sampling error.                                                                                                                                                                                                                                                                                                                                                                            |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Scanner Data          | Data ultimately derived from records created by retail checkout scanners. This is one form of **transaction data**.                                                                                                                                                                                                                                                                                                                                                                                                      |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Transaction Data      | Data that reflect actual purchases. Observations may represent individual transactions or aggregations of sales at a product level. Data include transaction prices and a measure of sales volume (quantity or expenditure). See **scanner data** above.                                                                                                                                                                                                                                                                 |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variety               | The different varieties of products you can get that have the same article code, for example different sizes or colours.                                                                                                                                                                                                                                                                                                                                                                                                 |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Web scraping          | A process of automated data collection where computer programs extract relevant data elements (such as list price and product details) from websites.                                                                                                                                                                                                                                                                                                                                                                    |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
