---
title: "Welcome to the handbook on utilising new data sources in the production of consumer price statistics!"
date: 2024-05-13
date-modified: last-modified
---

Developed by the [UN Task Team on Scanner Data](https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml), this handbook is intended for a broad audience, including national statistical offices, central banks, international organisations, and researchers involved in the development, implementation, or evaluation of consumer price indices. 

::: callout-note
## Deprecation of previous (wiki) version

This handbook used to be (and may be for a while) still available on [the UNstats wiki](https://unstats.un.org/wiki/spaces/GWGSD/pages/240910447/Handbook+on+utilising+new+data+sources+in+the+production+of+consumer+price+statistics).
That version has however been deprecated and will not be maintained.
All content and changes will be made to the current version you are on.
:::

## What is covered?

The Handbook covers a broad range of data sources - including transaction data such as scanner data, and non-transaction data such as web-scraped data - that differ to traditional collection in how prices are observed, recorded and accessed.
It is intended to support both organisations exploring these data sources for the first time, and those seeking to refine or extend existing implementations.

This Handbook complements Chapter 10 of the [CPI Manual, Concepts and Methods](https://www.ilo.org/sites/default/files/wcmsp5/groups/public/%40dgreports/%40stat/documents/publication/wcms_761444.pdf) by providing detailed operational guidance on the use of alternative data sources in CPI production.
It does not replace the CPI Manual, which sets out the underlying concepts, principles and governance framework for the use of alternative data sources in CPI compilation.

This Handbook covers key stages of the CPI production process where new data sources may be introduced, including data acquisition, preparation, classification, index compilation, quality assurance, and dissemination.
It brings together conceptual discussion, practical considerations, methodological options, and examples from country practices, with the aim of supporting informed decision-making rather than prescribing a single method or workflow.

## How to use the handbook

There is no single "correct" approach to using new data sources in CPI production.
The appropriate choices will depend on national circumstances, data availability, institutional arrangements, technical capacity, and user needs.
Accordingly, the purpose of this handbook is to present the range of available approaches, highlight their strengths and limitations, and provide guidance to help users assess what is most suitable for their particular context.

While the primary focus of this Handbook is on consumer price statistics, many of the data sources, processes, and systems discussed may also support other areas of official statistics.
Where relevant, considerations for broader statistical use are highlighted to support efficient and sustainable use of alternative data sources across statistical domains.

## What is the handbook based on

This Handbook draws on existing international manuals, methodological papers, and country experiences, while also improving the literature on topics where guidance is currently more limited, such as data acquisition strategies, classification challenges, and the handling of highly dynamic product universes.
Given the rapid pace of methodological and technological developments in this field, the handbook is designed as a living document.
It will be reviewed and updated over time to reflect new research, emerging best practices, and feedback from users.

## What else is included

Further to the handbook, we provide [self-paced learning courses](/training/index.qmd), [guidance on conducting reproducible research in price statistics](https://un-task-team-for-scanner-data.github.io/reproducibility-project/docs/), and a [catalog of open datasets](https://un-task-team-for-scanner-data.github.io/price-stats-data-catalogue/) applicable to price statistics research.
Read more [about us](https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml), explore this (and linked sites), and checkout [our GitHub group](https://github.com/UN-Task-Team-for-Scanner-Data) for more on our projects.

## Contributing feedback and future development

Users of this Handbook are encouraged to support its ongoing development and improvement.
Feedback may include suggestions on topics that could be expanded or added, identification of errors or areas requiring clarification, or proposals to refine existing content in light of new research or country experience.
Such feedback will help ensure that this Handbook remains relevant, accurate, and responsive to the evolving needs of the international statistical community.
Please see the [how to contribute guide](/about/contributing.qmd) for more information.

This Handbook is publicly available and intended to be used alongside related [training materials](/training/index.qmd) and other supporting resources developed by the UN Task Team on Scanner Data.

## How to cite {#how-to-cite}

The handbook is availible in [CC-BY 4.0 licence](https://github.com/UN-Task-Team-for-Scanner-Data/cpi-new-data-sources-handbook/blob/main/LICENCE).

You can confirm how to cite our handbook by citing the [latest release in Zenodo](https://doi.org/10.5281/zenodo.23192540).
Below is an example, although it may be out of date.

### BibTeX citation

``` bibtex
@software{un_task_team_on_scanner_data_2026_23192541,
  author       = {UN Task Team on Scanner Data},
  title        = {Handbook on new data sources in consumer price
                   statistics
                  },
  month        = oct,
  year         = 2026,
  publisher    = {Zenodo},
  version      = {0.1.0},
  doi          = {10.5281/zenodo.23192541},
  url          = {https://doi.org/10.5281/zenodo.23192541},
}
```

### Chicago

``` {.md .code-overflow-wrap}
UN Task Team on Scanner Data. Handbook on New Data Sources in Consumer Price Statistics. V. 0.1.0. Zenodo, released October 6, 2026. https://doi.org/10.5281/zenodo.23192541.
```