---
title: "Note on variables applicable for classification"
---

Several variables [obtained during the acquisition process](https://unstats.un.org/wiki/spaces/GWGSD/pages/101353236/ARCHIVE+Example+file+structures+for+web+scraped+and+scanner+data)  are typically applicable for classification. An important consideration is making sure that the appropriate variables are included when acquisition is being discussed, as it may be challenging to expand the set over time. The below table summarizes the variables commonly found useful, although this table should not mean that all variables are used. Studies should be done to make sure that only useful variables are used in the classification process (for example some variables may not be of much value to a classifier).

**Page information**

+---------------------+--------------------------------------------------------------------------------------------+
| Version             | v2                                                                                         |
+---------------------+--------------------------------------------------------------------------------------------+
| Last updated on     | 2024-04-28                                                                                 |
+---------------------+--------------------------------------------------------------------------------------------+
| Summary of changes  | Initial publication of the page                                                            |
+---------------------+--------------------------------------------------------------------------------------------+
| Page history        | [See here](https://unstats.un.org/wiki/pages/viewpreviousversions.action?pageId=337281178) |
+---------------------+--------------------------------------------------------------------------------------------+

Table 1: Summary of typical variables in alternative data and their application for classification

+:---------------------------------------------:+:---------------------------------------------------:+:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:+:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:+
| **Value for classification**                  | **Variable**                                        | **Definition and note on its application for classification**                                                                                                                                                                                                                                                                                                                                                             | **Note on data the variable is available in**                                                                                                                                                      |
+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| High                                          | Product name                                        | Actual product being sold. Useful for all but [Method 1](method-1-attribute-based-classification-method.qmd).                                                                                                                                                                                                                                                                                                                                                 | This variable is usually available everywhere. Web scrape definitions of product names may be unstable as a retailer may modify the name over time (such as adding "SALE" at the end of the name). |
+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| High                                          | Retailer category / categories                      | The retailer specific category or set of hierarchical categories. Most useful for rule-based approaches ([methods 1](method-1-attribute-based-classification-method.qmd) and [2](method-2-pattern-matching-classification-method.qmd)).                                                                                                                                                                                                                                                            | Usually available as retailer categories in scanner, or captured as a "breadcrumb" navigation variable on web scrape data.                                                                         |
+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| High                                          | Product identifier (ideally GTIN)                   | The unique identifier for the product, ideally the GTIN, the first 2 codes of which are country, then 3-7 are manufacturer/producer specific. This variable is heavily used by many NSOs. If GTIN is not available, other variables such as UPC or SKU could be useful, but these provide less value for classification.                                                                                                  | Usually provided with Scanner data, however not available in all countries. Web scrape data usually does not contain GTINs but may have SKUs or other retailer specific product numbers.           |
+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Medium                                        | Description                                         | Text description of the product. Useful for all but [Method 1](method-1-attribute-based-classification-method.qmd). For automated methods such as [methods 3](method-3-recommendation-machine-assisted-classification.qmd) and [4](method-4-machine-learning-classification-method.qmd), this is often the main variable that is used in the text processing pipeline to help predict the product class                                                                                                                                         | \                                                                                                                                                                                                  |
+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Medium                                        | Brand                                               | Brand of the manufacturer. Usually used in concatenation, and may be used by all but [method 1](method-1-attribute-based-classification-method.qmd). If GTIN is available, you can extract brand from there.                                                                                                                                                                                                                                                  | \                                                                                                                                                                                                  |
+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Low (but high for quality adjustment methods) | Product characteristics (sometimes called features) | Materials or other attributes of the product. This may be useful if classification needs nuanced terms such as materials (e.g. clothing) and is usually only adopted when the process is highly automated (such as [Methods 3](method-3-recommendation-machine-assisted-classification.qmd) and [4](method-4-machine-learning-classification-method.qmd)). Methods that apply [quality adjustment (such as hedonics)](quality-change-and-hedonic-estimation.qmd) use this type of data heavily.  | This variable is usually not provided in scanner data, but is available in web scrape and administrative data.                                                                                     |
+-----------------------------------------------+-----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
