---
title: "Product sampling for price index calculation"
date-modified: "2021-08-03"
---

NSOs can either choose to use all available data from their new data
source, or to use a sample of this data. In the first case, all sold
items' prices and quantities in all outlets are used in the price index
calculation. Items are typically weighted to reflect their economic
importance and an appropriate index formula is used (typically a
multilateral index method). No product or outlet sampling is needed in
this case. In the second case, a country may choose to sample from these
new data sources in order to replace the existing collection. Some
considerations on how to choose an appropriate product sample from these
data sources are given here.

------------------------------------------------------------------------

# Product sampling with scanner data {#Productsamplingforpriceindexcalculation-Productsamplingwithscannerdata}

The availability of quantities sold or revenues for each individual
product in scanner data provides opportunities for product sampling
strategies for price index calculation purposes. For instance, scanner
data generally represents a census of the retailer's outlets and
products sold during a given period. The process of filtering these data
down to those goods and services within the scope of a Consumer Price
Index (CPI) is covered in the section
\"[Classification](classification.qmd)\". Thus, a retailer's
scanner data (once classified) provides a sampling frame for statistical
sampling techniques for the selection of outlets and products in the
context of the CPI price survey.

The scanner data sampling frame can be used to design a non-judgmental
sampling strategy. Probability sampling methods for products selection
in the context of scanner data are discussed in Ref. 2. The results
suggest the systematic sampling proportional to expenditure as the best
performing method with unbiased price change estimates and relatively
low standard errors. The cut-off sampling method performed well also.
This might indicate that in the case of a small sample size, the
exclusion of low-selling products from the price index calculation does
not significantly affect the index series. While this result gives
support to the use of the cut-off sampling with scanner data, this
method may not be appropriate for some product categories in some
countries. The cut-off sampling method can be implemented using the
revenue share as a measure of the relative importance of products in
their product categories (see paragraphs 10.41-10.47 in [CPI Manual,
Concepts and
Methods](https://www.imf.org/-/media/Files/Data/CPI/cpi-manual-concepts-and-methods.ashx)
(2020)). For the maintenance of the sample over time, the revenue share
could help identify potential candidate products for replacement or
during a sample update.

The Eurostat\'s HICP - [Practical Guide for Processing Supermarket
Scanner
Data](https://circabc.europa.eu/ui/group/7b031f10-ac19-4da3-a36f-58708a70133d/library/8e1333df-ca16-40fc-bc6a-1ce1be37247c/details) (chapter
8) also discusses two sampling methods for scanner data processing: a
static sampling approach and a dynamic sampling approach. These
approaches are most commonly used to produce bilateral [price index
methods](price-index-methods.qmd), but in some instances the
dynamic approach can also be used as a way of preparing the data to feed
into multilateral indices, see for example Chapter 5 in Ref. 1.

The static sampling approach is very similar to the traditional field
collection sampling of the price survey except that the data collection
is done centrally instead of in-store visits by interviewers. A
representative sample of store locations can be selected using the store
level total revenue calculated over a recent period with a reasonable
length and the stores with the largest revenues selected in the sample.
Then, within a store and a product category, a representative product
sample is selected using sales data from a recent period with a
reasonable length, for example the previous six or twelve months. As a
selection criteria, one may include products that have been sold in each
of the preceding twelve months (stability) and that have the largest
revenue shares within their respective product categories
(representativeness). A threshold may be set for the cumulative revenue
share of the sampled products. Depending on the dispersion of sales
within the product category, this threshold could be set at 40%, 50%,
60%, etc. Each month, prices are collected for the sampled products
using the scanner data for that month.

Whenever a product is no longer available in the data set in a given
month, field collection substitution rules are applied. Also, it may be
desirable to replace a product as soon as its monthly sales become so
low that it could no longer be seen as representative for its product
category. It may also be acceptable to let products exit the market
before replacing them in the sample. When a replacement is required,
candidate products are identified based on product descriptions and
sales. The selected replacement products should be equivalent to the
disappeared ones in terms of quality. The previous month price of a
replacement product could either be looked for in the previous month
scanner data or imputed using a quality adjustment technique, similar to
rules in place for the field collection. Sales data may be monitored
over time and used to keep the product sample as representative as in
the initial month the sample was selected. A simplified version of the
static approach consists in a direct replacement of the field collection
product sample with a sample of products selected from scanner data for
a given retailer, using exactly the same sample of stores. The sample
size and the sampled outlets remain the same under the field collection.
It should be noted that when used in practice, there is sometimes
additional resource requirements to identifying suitable replacements
from the scanner data. The process by which replacements are chosen and
quality adjustments are made where necessary, can also have a
significant impact on the final index output. 

The dynamic sampling approach uses a set of filters and an algorithm to
select a matched sample of products for each month and the reference
month. The product sample comprises of products that are present in both
the current month and the reference month and that represent a
significant portion of sales in their respective product categories. The
product sample may vary from one month to the next. Given the use of
pre-set filters, the entire sampling procedure can be fully automated.
However, an automated system cannot necessarily handle product
relaunches well in the calculation of price relatives, because the
relaunched products cannot be conveniently linked to the old products in
an automated manner. Challenges raised by relaunches or other sources of
product churn make the dynamic sampling approach unsuitable for product
groups with a high turnover rate. The dynamic approach improves the
quality of price indexes based on scanner data, compared to field
collection price indexes or to the static sampling approach. In view of
the low level of manual interventions, it is cost efficient. As a
result, when the dynamic sampling approach is used, it is easy to extend
the use of scanner data to more retailers. A detailed discussion on the
dynamic sampling approach is available in section 8.3 of Eurostat\'s
HICP - [Practical Guide for Processing Supermarket Scanner
Data](https://circabc.europa.eu/ui/group/7b031f10-ac19-4da3-a36f-58708a70133d/library/8e1333df-ca16-40fc-bc6a-1ce1be37247c/details) .

While National Statistical Offices (NSOs) should attempt to use the full
universe of scanner data whenever possible, they may decide to use the
static or dynamic sampling method if the capacity of their systems and
processing infrastructure is limited. Using a sampling method may
represent the first stage of a gradual approach to the use of scanner
data in the CPI. When some minimum data processing capacity, skill set
and infrastructure become available, the NSO may eventually move to a
multilateral index method based on the universe of all available
products.

# Product sampling with web scraped data {#Productsamplingforpriceindexcalculation-Productsamplingwithwebscrapeddata}

If the NSO follows the targeted approach for scraping with web scraped
data (see section on [Strategies available for in-house web
scraping](strategies-available-for-in-house-web-scraping.qmd))
then this will already form your product sample.

When bulk web scraped data are available for some product categories
from some retailers, they provide opportunities to improve the accuracy
of the CPI through enhanced coverage of product dimensions such as time
and varieties. However, since there is no sale information in web
scraped data, the economic importance of individual products in their
respective product categories cannot be estimated. The two sampling
approaches previously discussed in the context of scanned data cannot be
employed. The [CPI Manual, Concepts and
Methods](https://www.imf.org/-/media/Files/Data/CPI/cpi-manual-concepts-and-methods.ashx)
(2020) briefly discusses a few considerations for using web-scraped
prices in the CPI calculation. For instance, web-scraped data can be
used as a replacement for the field collection for entire product
categories from one or more retailers. In this case, using price data
for all available individual products is the option likely to be chosen.
Indeed, it is not clear how a sample of products could be selected given
the lack of information on products' representativeness in their
categories. 

Before using web-scraped data from a given retailer in the CPI
calculation, it is important to verify if there are any differences
between web-listed and in-store list prices (or, ideally, transaction
prices) for this retailer. Any available information on possible
differences between these two types of prices should be taken into
consideration. The goal is to ensure that the web scraped prices used in
the CPI calculation reflect in-store prices as much as possible. For
example, if a retailer uses a regional pricing strategy, it is important
to collect and use appropriate local prices in the price index
calculation for the lowest level geographic regions.

\

------------------------------------------------------------------------

# References {#Productsamplingforpriceindexcalculation-References}

\(1\) Białek, J and Berȩsewicz, M (2021). Scanner data in inflation
measurement: From raw data to price indices.
<https://content.iospress.com/articles/statistical-journal-of-the-iaos/sji210816>

\(2\) De Haan, Opperdoes and Schut (1999). Item selection in the
Consumer Price Index: Cut-off versus probability sampling.
<https://www150.statcan.gc.ca/n1/en/pub/12-001-x/1999001/article/4710-eng.pdf?st=YdDlyaD4>
