---
title: "Selection of retailers for alternative data sources"
---

This page contains information on how to identify suitable retailers who can supply these alternative data sources\

**Page information**

+----------------------+--------------------------------------------------------------------------------------------+
| Version              | v2                                                                                         |
+----------------------+--------------------------------------------------------------------------------------------+
| Last updated on      | 2021-07-03                                                                                 |
+----------------------+--------------------------------------------------------------------------------------------+
| Summary of changes   | Initial publication version                                                                |
+----------------------+--------------------------------------------------------------------------------------------+
| Page history         | [See here](https://unstats.un.org/wiki/pages/viewpreviousversions.action?pageId=240910457) |
+----------------------+--------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

# Overview {#Selectionofretailersforalternativedatasources-Overview}

The scanner data technology for retail transactions is now used by most businesses in the retail sector. While all chain retailers have adopted its use for all their transactions, some local businesses do not have it due to its cost as well as the small scale of their operations. Among those who use this technology, not all of them have in place the infrastructure and the equipment required to produce scanner data files that record details on all cash register transactions. As a result, some of the retailers included in the Consumer Price Index (CPI) price survey outlet sample may not have any scanner data available. Similarly, the websites of large retailers generally provide useful and detailed information, including prices and descriptions for the online products while smaller ones may only provide limited information (contact information, available product lines, etc). In addition, statistical offices may not have a control on which retailers will eventually be providing access to their data through these two types of data collection mode. Depending on each country's legislations, the retailers' participation may or may not be made mandatory in regards to the Statistics Act. Thus, in practice it may not be possible to move to scanner data or to web scraped for all the retailers included in the price survey's field collection sample.

Whenever both scanner and web scraped data from a given retailer are equally accessible to a CPI program, scanner data should be preferred. Indeed, both types of data sources provide detailed product descriptions, even if the levels of detail are not exactly the same. Scanner data contain information for only products sold in the data reference period. Web scraped data contain information for all products advertised on the retailer's website at the time of the website scraping, some of which may not have been sold during the reference period. For the CPI calculation, prices based on actual transactions are preferable to list prices available in web scraped data. In addition, the sales revenue available in scanner data can be used in the estimation of expenditure shares for lower level product classes of the CPI classification, which helps improve the basket weights. A good practical strategy is to pursue the search for both options simultaneously as their outcome may be uncertain. This section discusses key considerations that may be useful in the selection of retailers for scanner data acquisition or for web scraping.

# Scanner data {#Selectionofretailersforalternativedatasources-Scannerdata}

The selection of potential retailers for scanner data acquisition can start from the list of retailers included in the existing CPI price survey (field collection, Internet collection, etc). Then, representativeness and market structure considerations can be used to set priority. The retailers' representativeness in their respective retail sector can be assessed using a variable such as annual sales revenue. The same data sources used for the selection of the field collection store sample, including the business register and retail commodity surveys, can be used. As much as possible, these data sources must allow the estimation of sales revenue by product category and by type of outlet (large retail stores, small retail stores, Internet sales, etc.). Large retailers with large market shares in certain sectors should get a higher priority compared to smaller retailers with low market shares. Then, a list of potential retailers for scanner data acquisition can be formed and data acquisition discussions initiated.

# Web scraping {#Selectionofretailersforalternativedatasources-Webscraping}

For the selection of retailers for web scraping, those retailers that cannot provide scanner data should be prioritized. In contrast, retailers with a highly regional pricing rule should be avoided for web scraping as many web access points might be needed for scraping in order to accurately reflect actual price movements occurring in all regions of the country. The Eurostat's manual "[Practical guidelines on web scraping for the HICP](https://ec.europa.eu/eurostat/documents/272892/12032198/Guidelines-web-scraping-HICP-11-2020.pdf/)" (chapter 4) discusses useful guidance and criteria for the selection of products for web scraping. Methodological considerations, for example related to the evolution of online sales for different product categories and different retailers need to be used in the selection of target product categories for web scraping. For instance, products that do not experience neither significant nor frequent quality change and products that are gaining popularity among online purchases are good candidates for a web scraping project. It is worth considering key website characteristics in the selection of retailers for scraping. These include representativeness of consumers' habits, volume of data available, technical characteristics of the website, stability of the website, metadata information, etc.

It may be useful to mention the case of third-party retailers that sell their products through the websites of larger and well-established retailers via online marketplaces. These can be helpful in providing a single source of data rather than having to scrape multiple different websites. However, there are arguments in favour to restricting web scraping activities to only products offered for sale by the selected retailers who own their websites. For example, if the products whose prices enter the CPI calculation need to be offered by retailers with some minimum market share, then further analyses may be required to decide which of the third-party sellers can be considered for the scraping of the selected websites. Inversely, if the number of third-party retailers is relatively small and they can be identified as popular among consumers, then their product offers should be considered for web scraping. The treatment of third-party retailers with respect to scraping from a selected website needs to be conducted on a case by case basis.

Overall, because small retailers may not have a fully operational website or may not generate scanner data files for their transactions, it is not clear at which point a CPI program could terminate its field collection price survey and solely rely on scanner data or web scraped data collections, which are more cost-efficient. There is a need to monitor the trend in e-commerce among consumers as well as the evolution of the use of technology in retail. For more information on how to aggregate the different data sources (field collection, plus scanner and web scraped data, please see the section \"[Aggregation](aggregation.qmd)\".

\
