---
title: "Selection of categories"
---

One of the initial steps in this process is the identification and selection of product categories to consider for the adoption of alternative data sources\

**Page information**

+----------------------+--------------------------------------------------------------------------------------------+
| Version              | v2                                                                                         |
+----------------------+--------------------------------------------------------------------------------------------+
| Last updated on      | 2022-02-09                                                                                 |
+----------------------+--------------------------------------------------------------------------------------------+
| Summary of changes   | Initial publication version                                                                |
+----------------------+--------------------------------------------------------------------------------------------+
| Page History         | [See here](https://unstats.un.org/wiki/pages/viewpreviousversions.action?pageId=240910456) |
+----------------------+--------------------------------------------------------------------------------------------+

------------------------------------------------------------------------

# Definition of a strategy for the selection of categories {#Selectionofcategories-Definitionofastrategyfortheselectionofcategories}

In the last decade National Statistical Offices (NSOs) all around the world have intensified the study and integration of alternative data sources into their Consumer Price Index (CPI) programs (Ref. 1, 2, 4, 9, 12, 13, 18, 21, 23, 24, 25, 26, 28). One of the initial steps in this process is the identification and selection of sectors of the basket to consider for the adoption of alternative data sources. 

The variety of experiences reporting studies (Ref. 1, 2, 4, 9, 12, 13, 18, 21, 23--26, 26, 28) on different elements of the CPI basket is growing fast as a consequence of the expansion of this field. However, as detailed along the sections of this wiki, adoption of alternative data sources for CPI production can be an intricate and complex process. In this sense, a gradual approach aiming at the study and introduction of elements of the basket according to given priority criteria are advisable to select a reduced number of sectors to start and map all the potential sectors that should be pursued (Ref. 8, 12, 21, 26). 

As different sectors of the basket might present different degrees of requirements according to IT system structure, methodological developments, and staff skills etc, a gradual introduction of elements allow the NSO to build the necessary capacity and expertise in a more parsimonious manner and pave the way for the incorporation of more elements through time (Ref. 8, 12, 21, 26). This approach also will highlight the challenges involved in the different stages of the process in the adoption of alternative data sources for CPI compilation. 

# Criteria to consider {#Selectionofcategories-Criteriatoconsider}

Different criteria can be used by NSOs for the choice of priority sectors to consider (see Ref. 12, 21, 26 for more concrete examples). Useful points to consider include the following.

## Data source availability and properties {#Selectionofcategories-Datasourceavailabilityandproperties}

Source availability is an important point to take into account while exploring alternative data sources for CPI. A strategy can be developed to cover different sectors via different sources according to the sources properties and availability (Ref. 2, 12, 21).

Data acquisition challenges can differ according to the different data sources of interest. To have in mind the peculiarities to get access to each data source is an important point for NSOs to define the strategy for the selection of sectors to explore via alternative data sources as it might impact the planning of a schedule for study and implementation of these data. For instance, [access to scanner data involves intense negotiations with the retailers](initial-steps-in-the-acquisition-of-scanner-data.qmd) and the first access to this source might take more time than web data.

When data is available for the same sector via different sources, scanner data should be preferred over web data with "similar" (prices and product descriptions) content as the former has superior data properties (Ref. 7, 8).

Scanner data sets are also superior to the web since it might provide a back series of data for initial research. Stability in the data supply should also be considered. Hence, access via stable sources or tools like APIs should be preferred over web scraping whenever possible (Ref. 8).

Since these data sources do not have a full overlap of the variables covered (see [Example file structures for web scraped and scanner data](https://unstats.un.org/wiki/display/GWGSD/Example+file+structures+for+web+scraped+and+scanner+data)), they can also be used in a complementary way for some circumstances. For instance, product attributes extracted from the web can be combined with scanner data for the development of more refined automatic models for aggregation and classification of products (clothing being a typical example) (Ref. 5) or for the use of hedonic techniques to deal with quality adjustment issues (for instance, in the sector of electronics (Ref. 10)).

## Representativity of the sector in the basket {#Selectionofcategories-Representativityofthesectorinthebasket}

This can take into account the representativity in terms of expenditures of the sector in the basket and/or the number of elements of the basket covered. The current burden in terms of price quotes manually collected to build a representative sample for the sector can also be a useful parameter to consider.

A strategy that prioritizes sectors with a higher degree of representativity is appealing as the efforts addressed will have a greater impact in the CPIs produced.

## Representativity of the retailers {#Selectionofcategories-Representativityoftheretailers}

For the sectors chosen it is important that the alternative data sources available encompass retailers with important representation of the market of interest (see further discussion in the [selection of retailer's section](selection-of-retailers-for-alternative-data-sources.qmd)). In this sense, sectors with a high degree of market coverage by a reduced number of retailers are appealing as they can minimize the data access demands while leading to more significant results in terms of CPI production.

## Methodological demands, human and IT resources {#Selectionofcategories-MethodologicaldemandshumanandITresources}

As discussed in the [Introduction to the new data source section](overview-of-alternative-data-sources.qmd), incorporation of alternative data sources into CPI can require lengthy [data preparation](preparation-of-data.qmd) processes and important methodological developments that are intensive in human and [IT](cpi-production-system-requirements.qmd) resources.

Some sectors can be more costly in this sense than others. As an example, treatment of groceries can be less demanding than clothing in terms of aggregation and classification of products (Ref. 20). Ref. 22 also suggests that scanner data for clothing can also be more subject to the effects of refunds than groceries which could require additional treatment.

Being aware of the methodological challenges that should be covered by different sectors is also beneficial in the choice of sectors to cover as this will have impact on the IT and human resources necessary to take into account such issues properly.

The decision on whether to use a sample or the whole data set (see [Product sampling for price index calculation](product-sampling-for-price-index-calculation.qmd)) of a given source also has different methodological and structural demands that should be evaluated by an NSO. 

# Examples and discussion of some common choices {#Selectionofcategories-Examplesanddiscussionofsomecommonchoices}

Within the list of the most common sectors being explored via alternative data sources one can find:

## Groceries {#Selectionofcategories-Groceries}

The exploration of grocery scanner data is usually the first choice of an NSO (Ref. 1, 7, 13, 22). This sector is appealing for this since in many countries, especially in Europe, the market is highly concentrated in a small number of big retailer chains that have a high degree of market coverage. Furthermore, this is a sector with a high representativity in the CPI baskets and demanding in terms of collection. In this case, scanner data can allow a substantial reduction on the collection burden and still provide an expansion of the stores covered as all the stores of a given chain will be covered instead of a sample.

Studies on the use of web data for this sector can also be found (Ref. 2, 3, 13). However, one should be careful about the representativity of online purchases in this sector which are still lower compared to physical stores.

## Clothing and footwear {#Selectionofcategories-Clothingandfootwear}

Experiences on the use of both scanner (Ref. 6) and web data (Ref. 3, 6, 13, 27) can be found for these sectors. These are also among the main candidates first explored for CPI compilers studying alternative data sources. Again, important reasons for this choice amounts to the representativity of the sector, significative reduction of collection burden and improvement of coverage and methodology.

As this market tends to be more segmented than groceries, acquisition of scanner data for the number of retailers required that can provide a high degree of market coverage here can be more cumbersome. Also, the representativity of online purchases for these sectors are usually higher than the case of groceries. For these reasons, even though use of scanner data is encouraged, web data might offer a quicker first approach for this field and many countries are developing studies on this latter source (Ref. 3, 6, 13, 27).

As mentioned above it should also be noted that data [classification](classification.qmd) and preparation can be more demanding here than for other sectors (Ref. 14, 20).

## Transportation services {#Selectionofcategories-Transportationservices}

This can include air fares (Ref. 23, 25), rail fares (Ref. 8), taxi (Ref. 8), ride sharing services (Ref. 15) etc.

Use of alternative data sources here can provide a significative reduction in the manual collection burden (Ref. 23, 25) and/or increase the product coverage. The compilation of more precise CPIs that cope with companies pricing strategies such as dynamic pricing via reservation seats practices (see appendices IV and VI in (Ref. 8) for examples regarding train tickets and taxi services, respectively, and (Ref. 15) for a example regarding ride sharing services) can also be a by product from the use of alternative data sources.

The concentration of the sector is also another key feature since a high degree of representativity can be obtained via a reduced number of data providers. In the case of the web, this could involve scraping a reduced number of sites.

## Accommodation services {#Selectionofcategories-Accommodationservices}

Studies with both scanner (Ref. 29) and web data (Ref. 3, 13, 16, 19) can be found for this sector. And again, its choice is appealing due to possible improvement of the coverage of companies and products considered, and a significant reduction on the collection burden.

In the absence of scanner data sets available, the segmentation of the sector can be overcome via the use of booking sites that aggregates information from a large number of companies providing such services (Ref. 16, 19).

## Electronics and household appliances  {#Selectionofcategories-Electronicsandhouseholdappliances}

Improvement of the items coverage and development of more robust treatments of quality adjustment issues are some of the benefits of the use of alternative data sources for for this sector. Some experiences in this sector can be found in (Ref. 2, 10, 13, 23, 25, 30).

Combination of scanner and web data can be beneficial here as the web offers a source richer in product attributes that can be combined with scanner data sets in order to refine classification and hedonic models (Ref. 10).

## Used cars and fuels {#Selectionofcategories-Usedcarsandfuels}

These sectors usually play an important role in the CPI basket in terms of expenditures. For the case of used cars, alternative data sources have shown to be useful to provide rich data sets that allow a cheap and effective way to compile quality adjusted indicators (Ref. 13). Sample coverage and refinement of CPIs for fuels can also be improved via means of alternative data sources as recent experiences have shown (Ref. 17, 24).

## Centrally collected items {#Selectionofcategories-Centrallycollecteditems}

For some sectors of the basket for which data is centrally collected or alternative data sources such as the web are already used for manual collection (even not in a centralized manner), resources for the adoption of alternative data sources might not be so intensive since special data treatments or methodological changes might not be necessary in these cases and integration of the data into production can be more straightforward in an initial phase.

As an example, chart items such as CDs and DVDs, tickets for concerts, museums, books, etc that are manually collected on websites might have the manual process replaced by an automated one via the use of [targeted web scraping](strategies-available-for-in-house-web-scraping.qmd) techniques (Ref. 3, 9, 18). 

# Case studies {#Selectionofcategories-Casestudies}

The number of experiences is growing as a consequence of the rapid expansion of this field. The Eurostat\'s guidelines on the use of web scraping for CPI purposes (Ref. 8) also point for electricity, insurances and medicines as possible candidates for the use of web data. Other case studies via this source also include rental of rooms and personal care (Ref. 13, 18). Regarding scanner data, potential use for homeware, fuels, personal care, leisure goods and sports equipment have also been reported (Ref. 11, 22).  Table 1 below provides a list with references of experiences in different sectors reported by different countries separated by the kind of source used.\

Table 1: List of experiences of different countries of use of alternative data sources for different basket sectors of the CPI (See [Overview of alternative data sources](overview-of-alternative-data-sources.qmd) for a definition of these data sources).

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Country\\Source                                                                                                                                                                            | Transaction data (including scanner)                                                                                                                  | Web Scraping                                                                                                                                                                                                                                                                                                                                                                                                                            | API                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Australia                                                                                                                                                                                  | Groceries (food, non-alcoholic beverages, tobacco, non-durable household goods, personal care goods, pets and related products)                       | Clothing, footwear, fashion accessories, alcohol, furnishings, pharmaceutical products, spare parts for motor vehicles, newspapers, magazines and stationery.                                                                                                                                                                                                                                                                           | None                                              |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Brazil                                                                                                                                                                                     | None                                                                                                                                                  | [airfares](https://eventos.fgv.br/sites/eventos.fgv.br/files/arquivos/u161/study_of_new_data_sources_snipc_lincoln_da_silva.pdf), [ride sharing services](https://unece.org/sites/default/files/2021-05/Session_4_Brazil_Paper.pdf)                                                                                                                                                                                                     | None                                              |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |   (in research)                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       | [electronics](https://eventos.fgv.br/sites/eventos.fgv.br/files/arquivos/u161/study_of_new_data_sources_snipc_lincoln_da_silva.pdf), [hotels](https://circabc.europa.eu/ui/group/7b031f10-ac19-4da3-a36f-58708a70133d/library/e9fff896-7c7c-4e5b-a57d-9c5ab3effd8f/details?download=true), [household appliances](https://eventos.fgv.br/sites/eventos.fgv.br/files/arquivos/u161/study_of_new_data_sources_snipc_lincoln_da_silva.pdf) |                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Canada                                                                                                                                                                                     | Groceries (including food, alcohol and tobacco, household goods, health and personal care goods, magazines and newspapers)                            | Clothing, [computer equipment, software and supplies](https://www150.statcan.gc.ca/n1/en/catalogue/62F0014M2021004)                                                                                                                                                                                                                                                                                                                     | Airfares                                          |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         | \                                                 |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         | (in research)                                     |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         | Traveller accommodation                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Germany                                                                                                                                                                                    | (in research)                                                                                                                                         | Cruises, rail fares, coach transport services                                                                                                                                                                                                                                                                                                                                                                                           | Package holidays, airfares                        |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            | Groceries (including alcohol)                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Mexico                                                                                                                                                                                     | Pharmaceutical products                                                                                                                               | Groceries (including alcohol and tobacco), electronic goods (laptops, appliances), gas and natural gas                                                                                                                                                                                                                                                                                                                                  | \                                                 |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       | \                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       | (in research)                                                                                                                                                                                                                                                                                                                                                                                                                           |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       | Airfares                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Netherlands                                                                                                                                                                                | All COICOP divisions, except 04 and 10                                                                                                                | Clothing, footwear, furniture, airfares                                                                                                                                                                                                                                                                                                                                                                                                 | Consumer electronics, wireless telephone services |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Norway                                                                                                                                                                                     | Groceries (including alcohol, tobacco and personal care), clothing, electronics, pharmaceutical products, fuels, sports equipment, take away services | Electronic games, specialized items like sewing machines                                                                                                                                                                                                                                                                                                                                                                                | Airfares, electricity                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| Poland                                                                                                                                                                                     | (in research)                                                                                                                                         | (in research)                                                                                                                                                                                                                                                                                                                                                                                                                           | \                                                 |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            | groceries (excluding alcohol and tobacco), paper and hygiene articles,  products for cleaning and preserving, hygiene and cosmetic articles           | groceries (excluding alcohol and tobacco),                                                                                                                                                                                                                                                                                                                                                                                              |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            | \                                                                                                                                                     | pharmaceutical products                                                                                                                                                                                                                                                                                                                                                                                                                 |                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+
| United Kingdom                                                                                                                                                                             | Railfares                                                                                                                                             | (in research)                                                                                                                                                                                                                                                                                                                                                                                                                           | Used cars                                         |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
| Link: [overall strategy & associated research](https://www.ons.gov.uk/economy/inflationandpriceindices/articles/introducingalternativedatasourcesintoconsumerpricestatistics/november2021) | (in research)                                                                                                                                         | Clothing                                                                                                                                                                                                                                                                                                                                                                                                                                |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            | Groceries (including alcohol and tobacco)                                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            |                                                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
|                                                                                                                                                                                            | \                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                                   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------+

\

------------------------------------------------------------------------

# References {#Selectionofcategories-References}

\(1\) ABS 2016. *Making greater use of transactions data to compile the consumer price index, Australia*. [6401.0.60.003 - Information Paper: Making Greater Use of Transactions Data to compile the Consumer Price Index, Australia, 2016 (abs.gov.au)](https://www.abs.gov.au/AUSSTATS/abs@.nsf/mf/6401.0.60.003)

\(2\) Bentley, A. and Krsinich, F. 2017. Towards a big data CPI for New Zealand. *Paper presented at the 15th meeting of the Ottawa Group*. (2017). [Towards a big data CPI for New Zealand. (ottawagroup.org)](https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/4a256353001af3ed4b2562bb00121564/1ab31c25da944ff5ca25822c00757f87/$FILE/Towards%20a%20big%20data%20CPI%20for%20New%20Zealand%20-Alan%20Bentley,%20Frances%20Krsinich%20-%20Paper.pdf)

\(3\) Bhardwaj, H. et al. 2017. *Research indices using web scraped price data*. ONS. <https://www.ons.gov.uk/economy/inflationandpriceindices/articles/researchindicesusingwebscrapedpricedata/august2017update>

\(4\) Buron, M.-L. et al 2021. New data sources: The case of scanner data for the French consumer price index. *Paper presented at the online ILO/UNECE meeting of the Group of Experts on Consumer Price Indices*. (june 2021). <https://unece.org/sites/default/files/2021-05/Session_1_France.pdf>

\(5\) Chessa, A.G. 2019. MARS: A method for defining products and linking barcodes of item relaunches. *Paper presented at the 16th meeting of the Ottawa Group*. (May 2019). <https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/home/Meeting+16/$FILE/A%20method%20for%20defining%20products%20paper.pdf>

\(6\) Chessa, A.G. and Griffioen, R. 2019. Comparing price indices of clothing and footwear for scanner data and web scraped data. *Economie et Statistique.* 509 (2019), 49--68. <https://www.insee.fr/en/statistiques/4203548?sommaire=4203556>

\(7\) Eurostat 2017. *Practical guide for processing supermarket scanner data.* Eurostat. <https://circabc.europa.eu/sd/a/8e1333df-ca16-40fc-bc6a-1ce1be37247c/Practical-Guide-Supermarket-Scanner-Data-September-2017.pdf>

\(8\) Eurostat 2020. *Practical guidelines on web scraping for the hicp.* Eurostat. <https://ec.europa.eu/eurostat/documents/272892/12032198/Guidelines-web-scraping-HICP-11-2020.pdf/>

\(9\) Griffioen, R. and Bosch, O. ten 2016. ON the use of internet data for the Dutch CPI. *Paper presented at the ILO/UNECE Meeting of the Group of Experts on Consumer Price Indices.* (2016). <https://www.researchgate.net/publication/324896024_On_the_use_of_Internet_data_for_the_Dutch_CPI>

\(10\) Hov, K. 2021. New data sources for measuring price development on consumer electronics. *Work presented at the Eurostat Workshop on Scanner Data and Web Scraping*. (October 2021). <https://circabc.europa.eu/ui/group/7b031f10-ac19-4da3-a36f-58708a70133d/library/f6ef1d01-74cf-4409-a97c-ea41993f9f29/details?download=true>

\(11\) Hov, K.N. and Johannessen, R. 2018. Using scanner data for sports equipment. *Paper presented at the ILO/UNECE meeting of the Group of Experts on Consumer Price Indices*. (May 2018). <https://unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.22/2018/Norway_-_session_1.pdf>

\(12\) Konny, C.G. et al. 2019. Big data in the U.S. consumer price index: Experiences and plans. *Big Data for 21st Century Economic Statistics.* (June 2019). <https://www.brookings.edu/wp-content/uploads/2019/02/Big-Data-in-the-U.S.-Consumer-Price-Index.pdf>

\(13\) Loon, K.V. and Roels, D. 2018. Integrating big data in the Belgian CPI. *Paper presented at the ILO/UNECE meeting of the Group of Experts on Consumer Price Indices*. (May 2018). <https://unece.org/fileadmin/DAM/stats/documents/ece/ces/ge.22/2018/Belgium.pdf>

\(14\) Martindale, H. et al. 2019. Machine learning for classification with big data in price statistics production pipelines. *Paper presented at the 16th meeting of the Ottawa Group*. (May 2019). <https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/home/Meeting+16/$FILE/Machine%20learning%20for%20classification%20abstract.pdf>

\(15\) Miranda, V.G. et al. 2021. Measuring inflation of ride sharing services in Brazilian official CPIs. *Paper presented at the online ILO/UNECE meeting of the Group of Experts on Consumer Price Indices*. (June 2021). <https://unece.org/sites/default/files/2021-05/Session_4_Brazil_Paper.pdf>

\(16\) Montbroussous, A. 2021. Web scraping on [booking.com](http://booking.com) to implement a new hotel prices index. *Work presented at the Eurostat Workshop on Scanner Data and Web Scraping*. (October 2021). <https://circabc.europa.eu/ui/group/7b031f10-ac19-4da3-a36f-58708a70133d/library/cce09ee7-e1ec-4e64-be24-c5e6ba3a088f/details>

\(17\) Niedergall, S. 2021. Gasoline: Automated collection and the use of big data in the midst of the pandemic. *Work presented at the Eurostat Workshop on Scanner Data and Web Scraping*. (October 2021). <https://circabc.europa.eu/ui/group/7b031f10-ac19-4da3-a36f-58708a70133d/library/bc335eb9-5ca0-462d-a695-b9b0d2a9657e/details?download=true>

\(18\) Nygaard, R. 2015. The use of online prices in the Norwegian consumer price index. *Paper presented at the 14th meeting of the Group of Experts on Consumer Price Indices*. (May 2015). <https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/4a256353001af3ed4b2562bb00121564/d012f001b8a1cf6cca257eed008074c9/$FILE/Ragnhild%20Nygaard%20>(Statistics%20Norway-%20The%20use%20of%20online%20prices%20in%20the%20Norwegian%20Consumer%20Price%20Index.pdf

\(19\) Oliveira, I. et al. 2021. Using web scraping tools in collecting traveller accommodation prices to improve CPI compilation in brazil. *Work presented at the Eurostat Workshop on Scanner Data and Web Scraping*. (October 2021). <https://circabc.europa.eu/ui/group/7b031f10-ac19-4da3-a36f-58708a70133d/library/e9fff896-7c7c-4e5b-a57d-9c5ab3effd8f/details?download=true>

\(20\) ONS 2021. *Classification of new data in UK consumer price statistics*. <https://www.ons.gov.uk/economy/inflationandpriceindices/articles/classificationofnewdatainukconsumerpricestatistics/2021-04-06>

\(21\) ONS 2020. *Introducing alternative data sources into consumer price statistics*. <https://www.ons.gov.uk/economy/inflationandpriceindices/articles/introducingalternativedatasourcesintoconsumerpricestatistics/may2020>

\(22\) ONS 2021. *Research into the use of scanner data for constructing UK consumer price statistics.* <https://www.ons.gov.uk/economy/inflationandpriceindices/articles/researchintotheuseofscannerdataforconstructingukconsumerpricestatistics/2021-04-06>

\(23\) Polidoro, F. et al. 2014. Web scraping techniques to collect data on consumer electronics and airfares for Italian hicp compilation. *Statistical Journal of the IAOS.* (2014). <https://www.q2014.at/fileadmin/user_upload/1_FINAL_POLIDORO.pdf>

\(24\) Posse, R. and Reyes, J.A. 2019. Use of big data in modern markets coexisting with traditional markets data. *Paper presented at the 16th meeting of the Ottawa Group*. (May 2019). <https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/home/Meeting+16/$FILE/Use%20of%20Big%20Data%20in%20modern%20markets%20paper.pdf>

\(25\) Silva, L.T. da et al. 2019. Studies of new data sources and techniques to improve CPI compilation in brazil. *Paper presented at the 16th meeting of the Ottawa Group*. (May 2019). <https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/home/Meeting+16/$FILE/Studies%20of%20new%20data%20sources%20paper.pdf>

\(26\) Stahl, O. and Nilsson, P. 2019. Towards a roadmap for efficient use of electronic transaction data in the Swedish CPI. *Paper presented at the 16th meeting of the Ottawa Group*. (May 2019). <https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/home/Meeting+16/$FILE/Towards%20a%20Roadmap%20paper.pdf>

\(27\) Tomadini, A. and Holt, M. 2019. Experimental clothing indexes using Australian web scraped data. *Paper presented at the 16th meeting of the Ottawa Group*. (May 2019). [PowerPoint Presentation (ottawagroup.org)](https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/4a256353001af3ed4b2562bb00121564/e9607f2deb5949a9ca2584a800162343/$FILE/ABS%20web%20scraped%20data%20pres.pdf)

\(28\) Van, T.N. 2018. The practical experiences of collecting big data to compiling CPI of the general statistics office of Vietnam (GSO). *Paper presented at the ILO/UNECE meeting of the Group of Experts on Consumer Price Indices*. (May 2018).

\(29\) Wieland, E. 2019. Measuring price dynamics of package holidays with transaction data. *Paper presented at the 16th meeting of the Ottawa Group*. (May 2019). <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3587749>

\(30\) Zafar, J.-D. and Himpens, S. 2019. Web scraping laptop prices to estimate hedonic models and extensions to other predictive methods. *Paper presented at the 16th meeting of the Ottawa Group*. (May 2019). <https://www.ottawagroup.org/Ottawa/ottawagroup.nsf/home/Meeting+16/$FILE/Webscraping%20laptop%20prices%20paper.pdf>
