---
title: "Choosing an index method"
date-modified: "2024-03-01"
---

This section contains information on how an NSO can choose a suitable
index method. The choice of index method is an important part of
implementing these new data sources in production. It can be split into
two scenarios, one where expenditure data are available (this also
includes the scenario of web scraped for when there are proxy
expenditure weights available) and one where expenditure data are not
available.

Section contents:

- [Methods for when expenditure data are
  available](methods-for-when-expenditure-data-are-available.qmd)
  --- This page summarizes potential criteria that could be used by an
  NSO to decide on an index method for when expenditure data are
  available.
- [Methods for when expenditure data are not
  available](methods-for-when-expenditure-data-are-not-available.qmd)
  --- This page summarises potential criteria that could be used by an
  NSO to decide on an index method for when expenditure data are not
  available.
