---
title: "Common technical problems for in-house web scraping"
date-modified: "2021-08-09"
---

Overcoming some common technical problems for web scraping\

------------------------------------------------------------------------

# Common technical problems for in-house web scraping {#Commontechnicalproblemsforinhousewebscraping-Commontechnicalproblemsforin-housewebscraping}

Data extraction from websites through web scraping techniques for
production purposes in the consumer price index (CPI) compilation is
challenging. Around 75% of the countries covered in the Eurostat
questionnaire have experienced technical problems concerning web
scraping, see \"[Practical guidelines on web scraping for the
HICP](https://ec.europa.eu/eurostat/documents/272892/12032198/Guidelines-web-scraping-HICP-11-2020.pdf/)\".
While collecting information via crawlers for long periods several
technical issues may arise such as, web site structural changes,
internet protocol (IP) blocking, captchas, popups and even shut down of
a website. A backup solution is advised in case of interruption while
the scraping is not fixed and well-functioning again.

A good approach to prevent web scraping issues is to contact the website
owners in advance of web scraping to ask about anti-robot policies and
avoid getting your IP blocked. Establishing a good relationship with the
retailers might also provide more efficient solutions like getting
access via API or scanner data. Another advantage is to know beforehand
upcoming changes on the website and be able to modify crawler's code to
prevent its malfunctioning.

In general, websites require a tailor-made scraper for its extraction.
The maintenance of the web scraper requires dedicated staff to keep the
programs working properly. Even small modifications on the websites like
changes in the Xpath or css may lead to malfunction or inoperant
crawlers. It is common that websites modify nodes from time to time as
an anti-robot strategy. Using more stable Xpaths can prevent web
scrapers from failing when such minor changes occur. Nevertheless, it is
important to have in-house staff with programming skills and knowledge
of the codes to deal with these changes.

It is preferable to scrape websites that usually do not have regular
changes in its structure or HTML layout. It is not always possible to
know in advance whether modifications will occur, but a good strategy is
to perform some previous scraping of a target website some time before
implementing the robots for CPI production. However, there is no
guarantee that a website will not shut down as shown, for instance, in a
case example in annex VI of \"[Practical guidelines on web scraping for
the
HICP](https://ec.europa.eu/eurostat/documents/272892/12032198/Guidelines-web-scraping-HICP-11-2020.pdf/)\".

\
