---
title: "Data selection and acquisition"
date: "2024-05-13"
date-modified: "2026-05-13"
---

This section discusses how to select and acquire these new data sources. 
The goal of the section is to provide readers useful information on the complexities involved in obtaining these data as well as additional information such as the description of the data requirements that should be considered for the development of price statistics and the steps involved in the monitoring and validation of the data sets received.
As the marked differences in the nature of these data sources are also manifested in the procedures for data acquisition, a separate discussion is provided to deal with the peculiarities of each case. 

Section contents:

-   [Selection of categories](/handbook/selection-and-acquisition/selection-of-categories.qmd)
-   [Selection of retailers for alternative data sources](/handbook/selection-and-acquisition/selection-of-retailers-for-alternative-data-sources.qmd)
-   [Scanner data](/handbook/selection-and-acquisition/scanner/index.qmd)
-   [Web scraping](/handbook/selection-and-acquisition/web-scraped/index.qmd)
-   [Example file structures for web scraped and scanner data](/handbook/selection-and-acquisition/example-file-structures-for-web-scraped-and-scanner-data.qmd)
-   [Collection of data via APIs](/handbook/selection-and-acquisition/collection-of-data-via-apis.qmd)
-   [Dealing with unexpected data gaps](/handbook/selection-and-acquisition/dealing-with-unexpected-data-gaps.qmd)