---
title: "How to contribute"
date: 2026-09-29
date-modified: last-modified
draft: true
---

Welcome!
Thank you for your interest to contribute to this handbook.

::: callout-caution
## WIP

A draft is outlined below, however we are still finalizing the contributing process.
Please come back soon
:::

# Overview

## Semantic versioning

We use [semantic versioning](https://semver.org/) to guide us in how to make changes to our material.
Specifically:

| Level​ | Examples​ | Default route​ | Review expectation​ |
|:-------------------------|:--------------------------------------------------------------------|:---------------------------------------------------|:----------------------------------------------------------------------------------------|
| **PATCH**​ | Spelling, links, formatting, bibliography and other non-substantive corrections​ | Community issue or pull request using a GitHub template​ | Technical Secretariat check and merge once automated and editorial checks pass​ |
| **MINOR**​ | Case study, expanded example, factual clarification, evidence or code revision that does not change overall scope​ | Community or Task Team pull request​ | Relevant peer review and Steering Group approval​ |
| **MAJOR**​ | New chapter, substantial method, new data source, major restructuring or new training module​ | Task Team workstream / funded technical lead or consultant role​ | Documented peer review and Steering Group-level sign-off​ |

: Categoires of contribution {#tbl-contributing-categories .striped .hover}

## Archiving to Zenodo

We archive a copy of the repository to Zenodo during major increments (specifically during Major changes).
Specifically, when the handbook has accumulated enough conseqential changes from a previous major release (such as major changes or perhaps several minor ones), we [release a new version of the handbook](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository), which [archives a copy of the handbook](https://help.zenodo.org/docs/github/archive-software/github-upload/) to Zenodo.

You can see [our previous releases](https://github.com/UN-Task-Team-for-Scanner-Data/cpi-new-data-sources-handbook/releases).

## Gitflow process

All our contributions follow a basic Pull Request process, [similar to The Turing Way](https://book.the-turing-way.org/community-handbook/contributing/#ch-contributing-pull-request).

# Detail on how to contribute

## Step 1: Stat with an "issue"

First off, look through open issues to see if a topic has already been raised.
Either participate in a discussion on existing topics or start a new issue if you can't find a discussion on your topic.

-   If you are describing something that needs to change – please tell so that we can deal with it.
-   If you want to help us solve the problem (we encourage you to do so), describe what you would like to change. If the idea is approved, you can proceed to the next step.

## Step 2: Create a parallel copy (via a fork or new branch) and create a Pull Request (PR) to merge

Draft up changes that you want to make in a branch of your own fork of this repository.
Keep your PR as draft until it is ready to be reviewed.

::: callout-tip
## Update the last updated date!

Many of our pages start out with hard coded dates (read about the the typical [metadata in the style guide](/about/style-guide.qmd#metadata)).
Make sure you change `date-modified` to `last-modified` if you see it hard coded.
For example:

``` yml
--- 
title: "page title"
date: "2024-05-08" 
date-modified: "2025-10-08" # UPDATE THIS
---
```

Change to:

``` yml
---
title: "page title"
date: "2024-05-08" 
date-modified: last-modified
---
```
:::

## Step 3: Coordinate on review (only if needed)

If you are coordinating with others who don't use GitHub much and want to provide them an offline copy, you can integrate an export to [PDF](https://quarto.org/docs/reference/formats/pdf.html) or [MS word](https://quarto.org/docs/reference/formats/docx.html) in your article.
This will allow you to download a copy for offline use.
However, you will have to re-integrate these changes back into your fork.

``` md
---
title: "Article title"
date: "YYYY-MM-DD"
  pdf:
    documentclass: article
    papersize: letter
  docx:
    toc: true
---
```

## Step 4: Submit the PR

Once you are ready to merge your PR, remove the 'draft' status of the PR.
One of our team will support you through the rest of the process.
You may need to iterate on your changes if the material isn't yet ready to merge.

**That's it!!**