---
title: "About us"
date: 2026-09-29
date-modified: last-modified
draft: true
---

Welcome!
This project is maintained by the UN Task Team on Scanner data.

# Who are we?

## More about the Task Team

The Task Team on Scanner data is one of the workstreams stood up and supported by the CEBD.
Read more about us [here](https://unstats.un.org/bigdata/task-teams/scanner/index.cshtml).

## Who is on the Task Team?

Check out the acknowledgement section to see the full list of current and past participants

# Roster of experts

::: callout-note
## TBC

A roster of experts by topic will be added here
:::

# Our presentations

We are active in the price statistics space and have presented at several conferences.
Below is a notable list

::: callout-note
## WIP

A list of events we supported will be added soon
:::

# How to cite the handbook?

It is best to cite the latest release pushed to [our Zenodo repository](https://doi.org/10.5281/zenodo.23192540).
See an example on the [handbook home page](/index.qmd#how-to-cite).